# Generated by Django 6.0.2 on 2026-03-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Product_name',
            new_name='product_name',
        ),
    ]
