# Generated by Django 6.0.2 on 2026-03-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_rename_product_name_products_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created_date'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
